env:
  browser: true
  es2021: true
  node: true

extends:
  - "eslint:recommended"
  
parserOptions:
  ecmaVersion: 13
  parser: "@typescript-eslint/parser"
  sourceType: module

plugins:
  - "@typescript-eslint"

